const pressQuotes = [
    { id: 1, presenter: 'Utah Festival Opera', production: 'Le nozze di Figaro', preview: `"Gan is exquisite as the countess..."`, role: 'Countess Almaviva', content: `I must kowtow to Bridgette Gan who plays the Countess Almaviva, the long suffering wife of the womanizing Count. Gan is exquisite as the Countess. Her first aria that opens Act II, “Porgi, amor, qualche ristoro,” (or, “Grant, love, some comfort“) is beautifully sung and staged by director Suzan Hanson. The Countess stands, her back to the audience, framed in an archway, her thoughts assuredly on her husband. Gan sings this heartfelt aria wrenchingly, with artistry and amazing control. Hanson and Gan trust the music to carry the moment, keeping the action simple. Gan's Act III aria, “Dove sono i bei momenti” is just as exquisite with Gan adding embellishments and nuances I've never heard before, which deepens its lush beauty.`, author: 'Elizabeth Hansen', publication: 'Utah Theatre Bloggers'  },
    { id: 2, presenter: 'Utah Festival Opera', production: 'Le nozze di Figaro', role: 'Countess Almaviva', preview: `"It was heartfelt and pointed, and labeled Gan as the one to listen to..."`, content: `As Act II opened, Countess Almaviva (Bridgette Gan) provided a production highlight with her lamentation over her husband's infidelity. It was heartfelt and pointed, and labeled Gan as the one to listen to.`, author: 'Jay Wamsley', publication: 'Deseret news' },
    { id: 3, presenter: 'Utah Festival Opera', production: 'Le nozze di Figaro', role: 'Countess Almaviva', preview: `"Ms. Gan nicely balances what could have been contradictory roles as a tragically estranged spouse and a playfully amused object of a juvenile suitor's affections..."`, content: `Director Suzan Hanson gets marvelous performances from her entire cast, especially Rose-Antoinette Bellino and Bridgette Gan. Both women are impressive vocalists and their superb acting is just frosting on the cake.  As Rosina, the Countess Almaviva, Ms. Gan nicely balances what could have been contradictory roles as a tragically estranged spouse and a playfully amused object of a juvenile suitor's affections.`, author: 'Charlie Schill', publication: 'Utah Public Radio' },
    { id: 4, presenter: 'Utah Festival Opera', production: 'Masterclass', role: 'Sharon', preview: `"Bridgette Gan, as Sharon, the second Soprano is perfect in the role..."`, content: `Bridgette Gan, as Sharon, the second Soprano is perfect in the role, and when she and Hanson interact, Hanson's innate vulnerability and love of opera works.`, author: 'Elizabeth Hansen', publication: 'Utah Theatre Bloggers' },
    { id: 5, presenter: 'Utah Festival Opera', production: 'Masterclass', role: 'Sharon', preview: `"Bridgette Gan beautifully performs an aria from “Macbeth”..."`, content: `Supporting cast members add lust and depth to the drama...Bridgette Gan beautifully performs an aria from “Macbeth”`, author: 'Charlie Schill', publication: 'The Herald Journal' },
    { id: 6, presenter: 'St. Petersburg Opera', production: `L'elisir d'amore`, role: 'Adina', preview: `"It was hard to watch her performance and imagine anyone else playing Adina..."`, content: `But the real draw is the promising Bridgette Gan as Adina, who made a strong impression in her St. Petersburg Opera debut. From her opening aria, Of the Cruel Isolda, Gan captures the ear and eye with power and precision. She also made use of other bel canto staples, such as the gradual crescendo and decrescendo, a portamento or glide between notes, and the artful gesture as part of a song's delivery. It was hard to watch her performance and imagine anyone else playing Adina.`, author: 'Andrew Meacham', publication: 'Tampa Bay Times' },
    { id: 7, presenter: 'Opera Orlando', production: 'Don Pasquale', role: 'Norina', preview: `"when Pasquale calls her a minx, you believe it..."`, content: `Gan, who sports a clear, ringing soprano, has a saucy sparkle in her eyes--when Pasquale calls her a minx, you believe it.`, author: 'Matthew J. Palm', publication: 'Orlando Sentinel' },
    { id: 8, presenter: 'Opera Orlando', production: 'The Impresario', role: 'Bethany Squeals', preview: `"Bridgette Gan particularly sparkles..."`, content: `A tarted-up Bridgette Gan particularly sparkles, vocally and comically.`, author: 'Matthew J. Palm', publication: 'Orlando Sentinel' },
    { id: 9, presenter: 'Palm Beach Opera', production: 'Opera on the Waterfront', role: 'Zerbinetta', preview: `"She'll fill seats with a command of vocal pyrotechnics like hers..."`, content: `Next came the amazing Bridgette Gan, a fellow last year, now an opera star. Her soprano could break glass: the range is sensational and her pitch, perfection, as she sang Zerbinetta's Rondo from Strauss's Ariadne Auf Naxos. Impresarios will be happy to hire her. She'll fill seats with a command of vocal pyrotechnics like hers.`, author: 'Rex Hearn', publication: 'Palm Beach Arts Paper' },
    { id: 10, presenter: 'Palm Beach Opera', production: 'The Daughter of the Regiment', role: 'Marie', preview: `"Gan has lovely crystal clear high notes and a comic presence..."`, content: `Singing the role of Marie Saturday night was Palm Beach Opera Young Artist, Bridgette Gan (soprano). The role of Marie is a blend of coloratura and comic gags. Gan has lovely crystal clear high notes and a comic presence that brings to mind a slightly more refined Elly May Clampett.`, author: 'Nate Sykes', publication: 'The Shot Glass Review' },
    { id: 11, presenter: 'Palm Beach Opera', production: 'The Daughter of the Regiment', role: 'Marie', preview: `"Gan's performance as Marie was a great star turn..."`, content: `The cast for Saturday's performance featured a member of the Palm Beach Opera Young Artist program, Bridgette Gan, stepping into the role of Marie in place of another soprano who was ill.  Gan came in and gave a tour de force performance as Marie. Her voice has a rich tone with sparkling high notes. Her first aria, "Chacun le sait, Chacun le dit,"was beautifully sung and her second act show pieces, the melancholy "Par le rang et par l'opulence and the rousing "Salut a la France," were just as expertly and artfully sung. Gan delivered a vocally beautiful and consistent performance....Gan's performance as Marie was a great star turn for this young singer who has a world of potential in front of her.`, author: 'Jack Gardner', publication: 'Edge Media Network' },
    { id: 12, presenter: 'Palm Beach Opera', production: 'Opera on the Waterfront', role:'Soloist', preview: `"Soprano Gan proved that she has the vocal as well as acting ability and stage presence to do this aria justice..."`, content: `"Glitter and Be Gay" from Leonard Bernstein's operetta "Candide" is one of the few pieces that crosses over between the operatic and musical theater repertories. It is a difficult piece to sing with a lot of florid coloratura and several high E flats. It also requires a lot of acting ability to pull off. Soprano Gan proved that she has the vocal as well as acting ability and stage presence to do this aria justice.`, author: 'Jack Gardner', publication: 'Edge Media Network' },
    { id: 13, presenter: 'Palm Beach Opera', production: 'Opera on the Waterfront', role:'Soloist', preview: `"Soprano Bridgette Gan wowed the audience..."`, content: `Soprano Bridgette Gan wowed the audience with her fantastic and brilliant singing of “Glitter and Be Gay,” from Leonard Bernstein's Candide. She was sensational, and got the loudest applause.`, author: 'Rex Hearn', publication: 'Palm Beach Arts Paper'},
    { id: 14, presenter: 'Palm Beach Opera', production: 'Alcina', role: 'Morgana', preview: `"her runs were perfection..."`, content: `Ever threatening, Gan's evil side was very convincing… her runs were perfection. After her touching scene with Bradamante posing as Ricciardo, Gan lets off a bunch of Handelian “fireworks” that could be heard in the Florida Keys. What a joy to hear her sing with such earnest conviction.`, author: 'Rex Hearn', publication: 'Palm Beach Arts Paper' },
    { id: 15, presenter: 'Maryland Opera Studio', production: 'The Abduction from the Seraglio', role: 'Konstanze', preview: `"a gorgeous Konstanze..."`, content: `a gorgeous Konstanze…has the kind of lovely and flexible voice that can navigate intricate coloratura one minute and deliver a subtle put-down the next.`, author: 'Joan Reinthaler', publication: 'The Washington Post' },   
]

const list = () => {
    return [...pressQuotes] 
  }; 
  
const find = (id) => {
const review = pressQuotes.find(post => post.id === +id);
return {...review};
}

const findAll = (production) => {
    const prodReviews = pressQuotes.filter(show => production === show.production);
    return prodReviews;
}

module.exports = {
    list,
    find,
    findAll
}  